from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    """String enum with readable serialization."""

    def __str__(self) -> str:
        return self.value


class ImageSource(StrEnum):
    CURRENT_MAP = "CURRENT_MAP"
    CURRENT_VALIDATION = "CURRENT_VALIDATION"
    HISTORICAL_UPDATE = "HISTORICAL_UPDATE"


class QualityStatus(StrEnum):
    GOOD = "QUALITY_GOOD"
    BORDERLINE = "QUALITY_BORDERLINE"
    REJECT = "QUALITY_REJECT"


class RegistrationStatus(StrEnum):
    DIRECT_STRONG = "DIRECT_STRONG"
    DIRECT_WEAK = "DIRECT_WEAK"
    AMBIGUOUS_MULTIMODAL = "AMBIGUOUS_MULTIMODAL"
    QUALITY_REJECT = "QUALITY_REJECT"
    DIRECT_FAILED = "DIRECT_FAILED"
    BRIDGE_STRONG = "BRIDGE_STRONG"
    BRIDGE_WEAK = "BRIDGE_WEAK"


class FailureClass(StrEnum):
    BAD_IMAGE = "BAD_IMAGE"
    AMBIGUOUS_ALIAS = "AMBIGUOUS_ALIAS"
    HISTORICAL_SCENE_CHANGE = "HISTORICAL_SCENE_CHANGE"
    VIEWPOINT_GAP = "VIEWPOINT_GAP"
    UNRESOLVED = "UNRESOLVED"


class ReferenceState(StrEnum):
    HIST_CANDIDATE = "HIST_CANDIDATE"
    HIST_REGISTERED = "HIST_REGISTERED"
    HIST_STABLE = "HIST_STABLE"
    HIST_ACTIVE = "HIST_ACTIVE"
    HIST_SUSPECT = "HIST_SUSPECT"
    HIST_RETIRED = "HIST_RETIRED"
    HISTORICAL_ONLY = "HISTORICAL_ONLY"
    REDUNDANT = "REDUNDANT"
    QUARANTINE = "QUARANTINE"
    REJECTED = "REJECTED"


class ReferenceProvenance(StrEnum):
    CURRENT = "CURRENT"
    DIRECT = "DIRECT"
    BRIDGED = "BRIDGED"


class GeometryProvenance(StrEnum):
    CURRENT_REAL = "CURRENT_REAL"
    CURRENT_FEEDFORWARD_VERIFIED = "CURRENT_FEEDFORWARD_VERIFIED"
    VIRTUAL_BA_ONLY = "VIRTUAL_BA_ONLY"
    HISTORICAL_GEOMETRY_ONLY = "HISTORICAL_GEOMETRY_ONLY"


class MaskLabel(int, Enum):
    INVALID = 0
    STABLE = 1
    CHANGED = 2
    UNCERTAIN = 3


class ExperimentId(StrEnum):
    E0_BASE_CURRENT_ONLY = "E0_BASE_CURRENT_ONLY"
    E1_DIRECT_NO_CHANGE_MASK = "E1_DIRECT_NO_CHANGE_MASK"
    E2_DIRECT_CHANGE_AWARE = "E2_DIRECT_CHANGE_AWARE"
    E3_DIRECT_VERIFIED_BRIDGE = "E3_DIRECT_VERIFIED_BRIDGE"
    E4_SELECTED_AUGMENTED = "E4_SELECTED_AUGMENTED"
    E5_PRODUCTION_CANDIDATE = "E5_PRODUCTION_CANDIDATE"


class ValidationGrade(StrEnum):
    INDEPENDENT_CURRENT_SESSION = "INDEPENDENT_CURRENT_SESSION"
    LEAVE_ONE_SESSION_OUT = "LEAVE_ONE_SESSION_OUT"
    PROVISIONAL_PROXY_VALIDATION = "PROVISIONAL_PROXY_VALIDATION"
    NO_VALIDATION = "NO_VALIDATION"
